export interface ServiceState {
  tags:     Tag[];
  services: Service[];
  service: Service;
  banners: Banner[];
  searchText: string;
  searchArray:Service[];
  searchServices:Service[];
}

export interface eta {
  data: string;
  errors?: null;
  meter_text: string;
  meter: number;
  time: string;
  seconds: number;
}

export interface Service {
  id:                 number;
  parent_id:          number;
  name:               Name;
  image:              string;
  marker:             Marker;
  fixed:              number;
  price:              number;
  type_price:         number;
  calculator:         Calculator;
  description:        Name | null;
  status:             number;
  deleted_at:         null;
  created_at:         string;
  updated_at:         string;
  children_recursive: Service[];
  pivot?:             Pivot;
}

export enum Calculator {
  Fixed = "FIXED",
}

export interface Name {
  en: string;
}

export enum Marker {
  ImgCarsSedanMarkerPNG = "/img/cars/sedan_marker.png",
}

export interface Pivot {
  tag_id:        number;
  taggable_type: string;
  taggable_id:   number;
  taggables?:    null;
}

export interface Tag {
  id:            number;
  name:          string;
  slug:          null;
  color:         string;
  image:         null;
  type:          null;
  position:      null;
  status:        string;
  created_at:    string;
  updated_at:    string;
  related:       Pivot[];
  service_types: Service[];
}

// Generated by https://quicktype.io

export interface Banner {
  id:         number;
  url:        string;
  video:      null;
  click_url:  string;
  position:   number;
  status:     string;
  created_at: string;
  updated_at: string;
  image:      string;
}

// Generated by https://quicktype.io

export interface User {
  id:                     number;
  first_name:             string;
  last_name:              string;
  email:                  string;
  payment_mode:           string;
  user_type:              string;
  gender:                 string;
  country_code:           null;
  mobile:                 string;
  device_token:           string;
  device_id:              string;
  device_type:            string;
  login_by:               string;
  language:               string;
  qrcode_url:             null;
  referral_unique_id:     null;
  referal_count:          number;
  trial_ends_at:          null;
  avatar:                 null;
  social_unique_id:       null;
  latitude:               null;
  longitude:              null;
  stripe_cust_id:         null;
  wallet_balance:         number;
  otp:                    number;
  email_verified_at:      string;
  blocked:                string;
  deleted_at:             null;
  created_at:             string;
  updated_at:             string;
  currency:               string;
  sos:                    string;
  app_contact:            string;
  measurement:            string;
  cash:                   number;
  debit_machine:          number;
  voucher:                number;
  online:                 number;
  card:                   number;
  payumoney:              number;
  paypal:                 number;
  paypal_adaptive:        number;
  braintree:              number;
  paytm:                  number;
  stripe_secret_key:      string;
  stripe_publishable_key: string;
  stripe_currency:        null;
  payumoney_environment:  null;
  payumoney_key:          null;
  payumoney_salt:         null;
  payumoney_auth:         null;
  paypal_environment:     null;
  paypal_currency:        null;
  paypal_client_id:       null;
  paypal_client_secret:   null;
  braintree_environment:  null;
  braintree_merchant_id:  null;
  braintree_public_key:   null;
  braintree_private_key:  null;
  referral_count:         string;
  referral_amount:        string;
  referral_text:          string;
  referral_total_count:   string;
  referral_total_amount:  number;
  referral_total_text:    string;
  ride_otp:               number;
  ride_toll:              number;
  rating:                 number;
}
