// Generated by https://quicktype.io

import { ServiceType } from "./booking";

export interface Setting {
  serviceTypes: ServiceType[];
  referral:     Referral;
  about:        Static;
  term:         Static;
  privacy:      Static;
  token:        string;
  show:        boolean;
  tag:          Tag[];
}

export interface Static {
  id:         number;
  key:        string;
  value:      string;
  created_at: string;
  updated_at: string;
}

export interface Referral {
  referral:  string;
  count:     string;
  amount:    string;
  ride_otp:  number;
  ride_toll: number;
}

export interface Tag {
  id:         number;
  name:       string;
  slug:       null;
  color:      string;
  image:      null;
  type:       string;
  position:   null;
  status:     string;
  created_at: string;
  updated_at: string;
  faqs:       FAQ[];
}

export interface FAQ {
  id:         number;
  question:   string;
  answer:     string;
  status:     string;
  created_at: string;
  updated_at: string;
  pivot:      Pivot;
}

export interface Pivot {
  tag_id:        number;
  taggable_id:   number;
  taggable_type: string;
}
